# Generated by Django 5.1.2 on 2024-10-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
