# Generated by Django 5.1.2 on 2024-10-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delete_product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
